# Generated by Django 6.0 on 2025-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='user',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
