# Generated by Django 6.0 on 2025-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_scan_user_scanresult_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='details',
        ),
        migrations.AlterField(
            model_name='scan',
            name='normalized_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='risk_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='verdict',
            field=models.CharField(max_length=50),
        ),
    ]
