# Generated by Django 6.0 on 2025-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_remove_scanresult_details_alter_scan_normalized_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='normalized_url',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='status',
        ),
        migrations.AddField(
            model_name='scan',
            name='reason',
            field=models.TextField(default='Scanning in progress'),
        ),
        migrations.AddField(
            model_name='scan',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='verdict',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
